/* Generated by Yosys 0.9 (git sha1 1979e0b) */

(* top =  1  *)
(* src = "rtl/unsigned_mult.sv:1" *)
module unsigned_mult(clk, rstn, a, b, out);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  (* src = "rtl/unsigned_mult.sv:26|rtl/register16bit.sv:12|/usr/bin/../share/yosys/ice40/cells_map.v:12" *)
  wire _149_;
  (* src = "rtl/unsigned_mult.sv:8" *)
  input [7:0] a;
  (* src = "rtl/unsigned_mult.sv:12" *)
  wire [7:0] a_reg;
  (* src = "rtl/unsigned_mult.sv:9" *)
  input [7:0] b;
  (* src = "rtl/unsigned_mult.sv:13" *)
  wire [7:0] b_reg;
  (* src = "rtl/unsigned_mult.sv:6" *)
  input clk;
  (* src = "rtl/unsigned_mult.sv:14" *)
  wire [15:0] mul_val;
  (* src = "rtl/unsigned_mult.sv:10" *)
  output [15:0] out;
  (* src = "rtl/unsigned_mult.sv:15" *)
  wire [15:0] out_reg;
  (* src = "rtl/unsigned_mult.sv:18|rtl/register8bit.sv:6" *)
  wire \regA.clk ;
  (* src = "rtl/unsigned_mult.sv:18|rtl/register8bit.sv:8" *)
  wire [7:0] \regA.in ;
  (* src = "rtl/unsigned_mult.sv:18|rtl/register8bit.sv:10" *)
  wire [7:0] \regA.out ;
  (* src = "rtl/unsigned_mult.sv:18|rtl/register8bit.sv:9" *)
  wire [7:0] \regA.reg_value ;
  (* src = "rtl/unsigned_mult.sv:18|rtl/register8bit.sv:7" *)
  wire \regA.rstn ;
  (* src = "rtl/unsigned_mult.sv:20|rtl/register8bit.sv:6" *)
  wire \regB.clk ;
  (* src = "rtl/unsigned_mult.sv:20|rtl/register8bit.sv:8" *)
  wire [7:0] \regB.in ;
  (* src = "rtl/unsigned_mult.sv:20|rtl/register8bit.sv:10" *)
  wire [7:0] \regB.out ;
  (* src = "rtl/unsigned_mult.sv:20|rtl/register8bit.sv:9" *)
  wire [7:0] \regB.reg_value ;
  (* src = "rtl/unsigned_mult.sv:20|rtl/register8bit.sv:7" *)
  wire \regB.rstn ;
  (* src = "rtl/unsigned_mult.sv:26|rtl/register16bit.sv:6" *)
  wire \regOut.clk ;
  (* src = "rtl/unsigned_mult.sv:26|rtl/register16bit.sv:8" *)
  wire [15:0] \regOut.in ;
  (* src = "rtl/unsigned_mult.sv:26|rtl/register16bit.sv:10" *)
  wire [15:0] \regOut.out ;
  (* src = "rtl/unsigned_mult.sv:26|rtl/register16bit.sv:9" *)
  wire [15:0] \regOut.reg_value ;
  (* src = "rtl/unsigned_mult.sv:26|rtl/register16bit.sv:7" *)
  wire \regOut.rstn ;
  (* src = "rtl/unsigned_mult.sv:7" *)
  input rstn;
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:44" *)
  SB_LUT4 #(
    .LUT_INIT(4'h8)
  ) _150_ (
    .I0(\regA.reg_value [0]),
    .I1(\regB.reg_value [0]),
    .I2(1'h0),
    .I3(1'h0),
    .O(mul_val[0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h7888)
  ) _151_ (
    .I0(\regA.reg_value [0]),
    .I1(\regB.reg_value [1]),
    .I2(\regA.reg_value [1]),
    .I3(\regB.reg_value [0]),
    .O(mul_val[1])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:48" *)
  SB_LUT4 #(
    .LUT_INIT(8'h96)
  ) _152_ (
    .I0(_113_),
    .I1(_114_),
    .I2(_142_),
    .I3(1'h0),
    .O(mul_val[2])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:44" *)
  SB_LUT4 #(
    .LUT_INIT(4'h8)
  ) _153_ (
    .I0(\regA.reg_value [0]),
    .I1(\regB.reg_value [2]),
    .I2(1'h0),
    .I3(1'h0),
    .O(_113_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:44" *)
  SB_LUT4 #(
    .LUT_INIT(4'h8)
  ) _154_ (
    .I0(\regA.reg_value [2]),
    .I1(\regB.reg_value [0]),
    .I2(1'h0),
    .I3(1'h0),
    .O(_114_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h7000)
  ) _155_ (
    .I0(\regB.reg_value [0]),
    .I1(\regA.reg_value [0]),
    .I2(\regA.reg_value [1]),
    .I3(\regB.reg_value [1]),
    .O(_142_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:48" *)
  SB_LUT4 #(
    .LUT_INIT(8'h96)
  ) _156_ (
    .I0(_116_),
    .I1(_119_),
    .I2(_117_),
    .I3(1'h0),
    .O(mul_val[3])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:52" *)
  SB_LUT4 #(
    .LUT_INIT(16'hcf15)
  ) _157_ (
    .I0(_112_),
    .I1(_142_),
    .I2(_113_),
    .I3(_114_),
    .O(_116_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h8000)
  ) _158_ (
    .I0(\regA.reg_value [0]),
    .I1(\regB.reg_value [1]),
    .I2(\regA.reg_value [1]),
    .I3(\regB.reg_value [0]),
    .O(_112_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:48" *)
  SB_LUT4 #(
    .LUT_INIT(8'h4b)
  ) _159_ (
    .I0(_111_),
    .I1(_115_),
    .I2(_118_),
    .I3(1'h0),
    .O(_119_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:44" *)
  SB_LUT4 #(
    .LUT_INIT(4'h8)
  ) _160_ (
    .I0(\regA.reg_value [1]),
    .I1(\regB.reg_value [0]),
    .I2(1'h0),
    .I3(1'h0),
    .O(_111_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h7888)
  ) _161_ (
    .I0(\regA.reg_value [0]),
    .I1(\regB.reg_value [3]),
    .I2(\regB.reg_value [0]),
    .I3(\regA.reg_value [3]),
    .O(_118_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:44" *)
  SB_LUT4 #(
    .LUT_INIT(4'h8)
  ) _162_ (
    .I0(\regB.reg_value [1]),
    .I1(\regA.reg_value [2]),
    .I2(1'h0),
    .I3(1'h0),
    .O(_115_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:44" *)
  SB_LUT4 #(
    .LUT_INIT(4'h8)
  ) _163_ (
    .I0(\regA.reg_value [1]),
    .I1(\regB.reg_value [2]),
    .I2(1'h0),
    .I3(1'h0),
    .O(_117_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:48" *)
  SB_LUT4 #(
    .LUT_INIT(8'h69)
  ) _164_ (
    .I0(_120_),
    .I1(_129_),
    .I2(_121_),
    .I3(1'h0),
    .O(mul_val[4])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:48" *)
  SB_LUT4 #(
    .LUT_INIT(8'h41)
  ) _165_ (
    .I0(_116_),
    .I1(_119_),
    .I2(_117_),
    .I3(1'h0),
    .O(_120_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:48" *)
  SB_LUT4 #(
    .LUT_INIT(8'h69)
  ) _166_ (
    .I0(_124_),
    .I1(_125_),
    .I2(_128_),
    .I3(1'h0),
    .O(_129_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:48" *)
  SB_LUT4 #(
    .LUT_INIT(8'h78)
  ) _167_ (
    .I0(\regB.reg_value [1]),
    .I1(\regA.reg_value [3]),
    .I2(_123_),
    .I3(1'h0),
    .O(_124_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h7888)
  ) _168_ (
    .I0(\regA.reg_value [1]),
    .I1(\regB.reg_value [3]),
    .I2(\regB.reg_value [0]),
    .I3(\regA.reg_value [4]),
    .O(_123_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h0f77)
  ) _169_ (
    .I0(\regB.reg_value [3]),
    .I1(\regA.reg_value [0]),
    .I2(_115_),
    .I3(_118_),
    .O(_125_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h7888)
  ) _170_ (
    .I0(\regA.reg_value [0]),
    .I1(\regB.reg_value [4]),
    .I2(\regB.reg_value [2]),
    .I3(\regA.reg_value [2]),
    .O(_128_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h751f)
  ) _171_ (
    .I0(_117_),
    .I1(_111_),
    .I2(_115_),
    .I3(_118_),
    .O(_121_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:44" *)
  SB_LUT4 #(
    .LUT_INIT(4'h6)
  ) _172_ (
    .I0(_016_),
    .I1(_146_),
    .I2(1'h0),
    .I3(1'h0),
    .O(mul_val[6])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:44" *)
  SB_LUT4 #(
    .LUT_INIT(4'h9)
  ) _173_ (
    .I0(_001_),
    .I1(_014_),
    .I2(1'h0),
    .I3(1'h0),
    .O(_016_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:52" *)
  SB_LUT4 #(
    .LUT_INIT(16'hb22b)
  ) _174_ (
    .I0(_130_),
    .I1(_127_),
    .I2(_137_),
    .I3(_133_),
    .O(_001_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:48" *)
  SB_LUT4 #(
    .LUT_INIT(8'h71)
  ) _175_ (
    .I0(_124_),
    .I1(_128_),
    .I2(_125_),
    .I3(1'h0),
    .O(_130_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:48" *)
  SB_LUT4 #(
    .LUT_INIT(8'h69)
  ) _176_ (
    .I0(_134_),
    .I1(_136_),
    .I2(_135_),
    .I3(1'h0),
    .O(_137_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h007f)
  ) _177_ (
    .I0(\regA.reg_value [3]),
    .I1(_123_),
    .I2(\regB.reg_value [1]),
    .I3(_143_),
    .O(_134_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h8000)
  ) _178_ (
    .I0(\regA.reg_value [1]),
    .I1(\regB.reg_value [0]),
    .I2(\regB.reg_value [3]),
    .I3(\regA.reg_value [4]),
    .O(_143_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:48" *)
  SB_LUT4 #(
    .LUT_INIT(8'h78)
  ) _179_ (
    .I0(\regB.reg_value [0]),
    .I1(\regA.reg_value [5]),
    .I2(_144_),
    .I3(1'h0),
    .O(_136_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:44" *)
  SB_LUT4 #(
    .LUT_INIT(4'h8)
  ) _180_ (
    .I0(\regA.reg_value [2]),
    .I1(\regB.reg_value [3]),
    .I2(1'h0),
    .I3(1'h0),
    .O(_144_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:44" *)
  SB_LUT4 #(
    .LUT_INIT(4'h8)
  ) _181_ (
    .I0(\regB.reg_value [1]),
    .I1(\regA.reg_value [4]),
    .I2(1'h0),
    .I3(1'h0),
    .O(_135_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:44" *)
  SB_LUT4 #(
    .LUT_INIT(4'h8)
  ) _182_ (
    .I0(_113_),
    .I1(_126_),
    .I2(1'h0),
    .I3(1'h0),
    .O(_127_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:44" *)
  SB_LUT4 #(
    .LUT_INIT(4'h8)
  ) _183_ (
    .I0(\regA.reg_value [2]),
    .I1(\regB.reg_value [4]),
    .I2(1'h0),
    .I3(1'h0),
    .O(_126_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:48" *)
  SB_LUT4 #(
    .LUT_INIT(8'h78)
  ) _184_ (
    .I0(\regA.reg_value [0]),
    .I1(\regB.reg_value [5]),
    .I2(_132_),
    .I3(1'h0),
    .O(_133_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h7888)
  ) _185_ (
    .I0(\regA.reg_value [1]),
    .I1(\regB.reg_value [4]),
    .I2(\regB.reg_value [2]),
    .I3(\regA.reg_value [3]),
    .O(_132_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:48" *)
  SB_LUT4 #(
    .LUT_INIT(8'h69)
  ) _186_ (
    .I0(_002_),
    .I1(_010_),
    .I2(_013_),
    .I3(1'h0),
    .O(_014_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:52" *)
  SB_LUT4 #(
    .LUT_INIT(16'hd44d)
  ) _187_ (
    .I0(_133_),
    .I1(_134_),
    .I2(_136_),
    .I3(_135_),
    .O(_002_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:48" *)
  SB_LUT4 #(
    .LUT_INIT(8'h69)
  ) _188_ (
    .I0(_005_),
    .I1(_003_),
    .I2(_009_),
    .I3(1'h0),
    .O(_010_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:48" *)
  SB_LUT4 #(
    .LUT_INIT(8'h78)
  ) _189_ (
    .I0(\regB.reg_value [1]),
    .I1(\regA.reg_value [5]),
    .I2(_004_),
    .I3(1'h0),
    .O(_005_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h7888)
  ) _190_ (
    .I0(\regB.reg_value [0]),
    .I1(\regA.reg_value [6]),
    .I2(\regB.reg_value [3]),
    .I3(\regA.reg_value [3]),
    .O(_004_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h1777)
  ) _191_ (
    .I0(_135_),
    .I1(_144_),
    .I2(\regB.reg_value [0]),
    .I3(\regA.reg_value [5]),
    .O(_003_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:44" *)
  SB_LUT4 #(
    .LUT_INIT(4'h6)
  ) _192_ (
    .I0(_006_),
    .I1(_008_),
    .I2(1'h0),
    .I3(1'h0),
    .O(_009_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:44" *)
  SB_LUT4 #(
    .LUT_INIT(4'h8)
  ) _193_ (
    .I0(\regA.reg_value [1]),
    .I1(\regB.reg_value [5]),
    .I2(1'h0),
    .I3(1'h0),
    .O(_006_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h7888)
  ) _194_ (
    .I0(\regB.reg_value [2]),
    .I1(\regA.reg_value [4]),
    .I2(\regA.reg_value [2]),
    .I3(\regB.reg_value [4]),
    .O(_008_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:48" *)
  SB_LUT4 #(
    .LUT_INIT(8'h87)
  ) _195_ (
    .I0(\regA.reg_value [0]),
    .I1(\regB.reg_value [6]),
    .I2(_011_),
    .I3(1'h0),
    .O(_013_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h007f)
  ) _196_ (
    .I0(\regB.reg_value [5]),
    .I1(_132_),
    .I2(\regA.reg_value [0]),
    .I3(_145_),
    .O(_011_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h8000)
  ) _197_ (
    .I0(\regA.reg_value [1]),
    .I1(\regB.reg_value [2]),
    .I2(\regA.reg_value [3]),
    .I3(\regB.reg_value [4]),
    .O(_145_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:44" *)
  SB_LUT4 #(
    .LUT_INIT(4'h4)
  ) _198_ (
    .I0(_147_),
    .I1(_000_),
    .I2(1'h0),
    .I3(1'h0),
    .O(_146_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h9669)
  ) _199_ (
    .I0(_130_),
    .I1(_137_),
    .I2(_127_),
    .I3(_133_),
    .O(_000_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:48" *)
  SB_LUT4 #(
    .LUT_INIT(8'h71)
  ) _200_ (
    .I0(_120_),
    .I1(_129_),
    .I2(_121_),
    .I3(1'h0),
    .O(_147_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h8778)
  ) _201_ (
    .I0(_016_),
    .I1(_146_),
    .I2(_015_),
    .I3(_033_),
    .O(mul_val[7])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:44" *)
  SB_LUT4 #(
    .LUT_INIT(4'h4)
  ) _202_ (
    .I0(_001_),
    .I1(_014_),
    .I2(1'h0),
    .I3(1'h0),
    .O(_015_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:48" *)
  SB_LUT4 #(
    .LUT_INIT(8'h69)
  ) _203_ (
    .I0(_017_),
    .I1(_032_),
    .I2(_012_),
    .I3(1'h0),
    .O(_033_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:48" *)
  SB_LUT4 #(
    .LUT_INIT(8'h2b)
  ) _204_ (
    .I0(_002_),
    .I1(_010_),
    .I2(_013_),
    .I3(1'h0),
    .O(_017_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:48" *)
  SB_LUT4 #(
    .LUT_INIT(8'h69)
  ) _205_ (
    .I0(_018_),
    .I1(_027_),
    .I2(_031_),
    .I3(1'h0),
    .O(_032_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:48" *)
  SB_LUT4 #(
    .LUT_INIT(8'h71)
  ) _206_ (
    .I0(_005_),
    .I1(_009_),
    .I2(_003_),
    .I3(1'h0),
    .O(_018_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:48" *)
  SB_LUT4 #(
    .LUT_INIT(8'h69)
  ) _207_ (
    .I0(_019_),
    .I1(_022_),
    .I2(_026_),
    .I3(1'h0),
    .O(_027_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h007f)
  ) _208_ (
    .I0(\regA.reg_value [5]),
    .I1(_004_),
    .I2(\regB.reg_value [1]),
    .I3(_148_),
    .O(_019_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h8000)
  ) _209_ (
    .I0(\regB.reg_value [0]),
    .I1(\regB.reg_value [3]),
    .I2(\regA.reg_value [3]),
    .I3(\regA.reg_value [6]),
    .O(_148_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:44" *)
  SB_LUT4 #(
    .LUT_INIT(4'h6)
  ) _210_ (
    .I0(_020_),
    .I1(_021_),
    .I2(1'h0),
    .I3(1'h0),
    .O(_022_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:44" *)
  SB_LUT4 #(
    .LUT_INIT(4'h8)
  ) _211_ (
    .I0(\regB.reg_value [1]),
    .I1(\regA.reg_value [6]),
    .I2(1'h0),
    .I3(1'h0),
    .O(_020_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h7888)
  ) _212_ (
    .I0(\regB.reg_value [0]),
    .I1(\regA.reg_value [7]),
    .I2(\regB.reg_value [3]),
    .I3(\regA.reg_value [4]),
    .O(_021_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:44" *)
  SB_LUT4 #(
    .LUT_INIT(4'h6)
  ) _213_ (
    .I0(_023_),
    .I1(_025_),
    .I2(1'h0),
    .I3(1'h0),
    .O(_026_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:44" *)
  SB_LUT4 #(
    .LUT_INIT(4'h8)
  ) _214_ (
    .I0(\regA.reg_value [2]),
    .I1(\regB.reg_value [5]),
    .I2(1'h0),
    .I3(1'h0),
    .O(_023_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h7888)
  ) _215_ (
    .I0(\regB.reg_value [2]),
    .I1(\regA.reg_value [5]),
    .I2(\regA.reg_value [3]),
    .I3(\regB.reg_value [4]),
    .O(_025_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:44" *)
  SB_LUT4 #(
    .LUT_INIT(4'h6)
  ) _216_ (
    .I0(_030_),
    .I1(_028_),
    .I2(1'h0),
    .I3(1'h0),
    .O(_031_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h17e8)
  ) _217_ (
    .I0(_126_),
    .I1(_006_),
    .I2(_007_),
    .I3(_029_),
    .O(_030_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:44" *)
  SB_LUT4 #(
    .LUT_INIT(4'h8)
  ) _218_ (
    .I0(\regB.reg_value [2]),
    .I1(\regA.reg_value [4]),
    .I2(1'h0),
    .I3(1'h0),
    .O(_007_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:44" *)
  SB_LUT4 #(
    .LUT_INIT(4'h8)
  ) _219_ (
    .I0(\regA.reg_value [1]),
    .I1(\regB.reg_value [6]),
    .I2(1'h0),
    .I3(1'h0),
    .O(_029_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:44" *)
  SB_LUT4 #(
    .LUT_INIT(4'h8)
  ) _220_ (
    .I0(\regA.reg_value [0]),
    .I1(\regB.reg_value [7]),
    .I2(1'h0),
    .I3(1'h0),
    .O(_028_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:48" *)
  SB_LUT4 #(
    .LUT_INIT(8'h40)
  ) _221_ (
    .I0(_011_),
    .I1(\regA.reg_value [0]),
    .I2(\regB.reg_value [6]),
    .I3(1'h0),
    .O(_012_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:48" *)
  SB_LUT4 #(
    .LUT_INIT(8'h1e)
  ) _222_ (
    .I0(_052_),
    .I1(_053_),
    .I2(_034_),
    .I3(1'h0),
    .O(mul_val[8])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h1777)
  ) _223_ (
    .I0(_015_),
    .I1(_033_),
    .I2(_146_),
    .I3(_016_),
    .O(_034_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:44" *)
  SB_LUT4 #(
    .LUT_INIT(4'h4)
  ) _224_ (
    .I0(_035_),
    .I1(_051_),
    .I2(1'h0),
    .I3(1'h0),
    .O(_052_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:48" *)
  SB_LUT4 #(
    .LUT_INIT(8'h2b)
  ) _225_ (
    .I0(_017_),
    .I1(_032_),
    .I2(_012_),
    .I3(1'h0),
    .O(_035_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:48" *)
  SB_LUT4 #(
    .LUT_INIT(8'h96)
  ) _226_ (
    .I0(_037_),
    .I1(_050_),
    .I2(_036_),
    .I3(1'h0),
    .O(_051_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:48" *)
  SB_LUT4 #(
    .LUT_INIT(8'h2b)
  ) _227_ (
    .I0(_018_),
    .I1(_027_),
    .I2(_031_),
    .I3(1'h0),
    .O(_037_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:48" *)
  SB_LUT4 #(
    .LUT_INIT(8'h69)
  ) _228_ (
    .I0(_038_),
    .I1(_045_),
    .I2(_049_),
    .I3(1'h0),
    .O(_050_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:48" *)
  SB_LUT4 #(
    .LUT_INIT(8'h2b)
  ) _229_ (
    .I0(_019_),
    .I1(_022_),
    .I2(_026_),
    .I3(1'h0),
    .O(_038_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:44" *)
  SB_LUT4 #(
    .LUT_INIT(4'h6)
  ) _230_ (
    .I0(_041_),
    .I1(_044_),
    .I2(1'h0),
    .I3(1'h0),
    .O(_045_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h3c5a)
  ) _231_ (
    .I0(_122_),
    .I1(_020_),
    .I2(_040_),
    .I3(_021_),
    .O(_041_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:44" *)
  SB_LUT4 #(
    .LUT_INIT(4'h8)
  ) _232_ (
    .I0(\regB.reg_value [3]),
    .I1(\regA.reg_value [4]),
    .I2(1'h0),
    .I3(1'h0),
    .O(_122_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h7888)
  ) _233_ (
    .I0(\regB.reg_value [1]),
    .I1(\regA.reg_value [7]),
    .I2(\regB.reg_value [3]),
    .I3(\regA.reg_value [5]),
    .O(_040_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:44" *)
  SB_LUT4 #(
    .LUT_INIT(4'h6)
  ) _234_ (
    .I0(_042_),
    .I1(_043_),
    .I2(1'h0),
    .I3(1'h0),
    .O(_044_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:44" *)
  SB_LUT4 #(
    .LUT_INIT(4'h8)
  ) _235_ (
    .I0(\regA.reg_value [3]),
    .I1(\regB.reg_value [5]),
    .I2(1'h0),
    .I3(1'h0),
    .O(_042_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h7888)
  ) _236_ (
    .I0(\regB.reg_value [2]),
    .I1(\regA.reg_value [6]),
    .I2(\regA.reg_value [4]),
    .I3(\regB.reg_value [4]),
    .O(_043_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:44" *)
  SB_LUT4 #(
    .LUT_INIT(4'h6)
  ) _237_ (
    .I0(_048_),
    .I1(_046_),
    .I2(1'h0),
    .I3(1'h0),
    .O(_049_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h17e8)
  ) _238_ (
    .I0(_131_),
    .I1(_023_),
    .I2(_024_),
    .I3(_047_),
    .O(_048_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:44" *)
  SB_LUT4 #(
    .LUT_INIT(4'h8)
  ) _239_ (
    .I0(\regA.reg_value [3]),
    .I1(\regB.reg_value [4]),
    .I2(1'h0),
    .I3(1'h0),
    .O(_131_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:44" *)
  SB_LUT4 #(
    .LUT_INIT(4'h8)
  ) _240_ (
    .I0(\regB.reg_value [2]),
    .I1(\regA.reg_value [5]),
    .I2(1'h0),
    .I3(1'h0),
    .O(_024_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:44" *)
  SB_LUT4 #(
    .LUT_INIT(4'h8)
  ) _241_ (
    .I0(\regA.reg_value [2]),
    .I1(\regB.reg_value [6]),
    .I2(1'h0),
    .I3(1'h0),
    .O(_047_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:44" *)
  SB_LUT4 #(
    .LUT_INIT(4'h8)
  ) _242_ (
    .I0(\regA.reg_value [1]),
    .I1(\regB.reg_value [7]),
    .I2(1'h0),
    .I3(1'h0),
    .O(_046_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h0f77)
  ) _243_ (
    .I0(\regB.reg_value [6]),
    .I1(\regA.reg_value [1]),
    .I2(_028_),
    .I3(_030_),
    .O(_036_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:44" *)
  SB_LUT4 #(
    .LUT_INIT(4'h4)
  ) _244_ (
    .I0(_051_),
    .I1(_035_),
    .I2(1'h0),
    .I3(1'h0),
    .O(_053_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:48" *)
  SB_LUT4 #(
    .LUT_INIT(8'h1e)
  ) _245_ (
    .I0(_068_),
    .I1(_069_),
    .I2(_054_),
    .I3(1'h0),
    .O(mul_val[9])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:48" *)
  SB_LUT4 #(
    .LUT_INIT(8'h0e)
  ) _246_ (
    .I0(_053_),
    .I1(_034_),
    .I2(_052_),
    .I3(1'h0),
    .O(_054_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:44" *)
  SB_LUT4 #(
    .LUT_INIT(4'h4)
  ) _247_ (
    .I0(_055_),
    .I1(_067_),
    .I2(1'h0),
    .I3(1'h0),
    .O(_068_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:48" *)
  SB_LUT4 #(
    .LUT_INIT(8'hb2)
  ) _248_ (
    .I0(_037_),
    .I1(_050_),
    .I2(_036_),
    .I3(1'h0),
    .O(_055_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:48" *)
  SB_LUT4 #(
    .LUT_INIT(8'h96)
  ) _249_ (
    .I0(_057_),
    .I1(_066_),
    .I2(_056_),
    .I3(1'h0),
    .O(_067_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:48" *)
  SB_LUT4 #(
    .LUT_INIT(8'h2b)
  ) _250_ (
    .I0(_038_),
    .I1(_045_),
    .I2(_049_),
    .I3(1'h0),
    .O(_057_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:48" *)
  SB_LUT4 #(
    .LUT_INIT(8'h69)
  ) _251_ (
    .I0(_058_),
    .I1(_061_),
    .I2(_065_),
    .I3(1'h0),
    .O(_066_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:48" *)
  SB_LUT4 #(
    .LUT_INIT(8'h53)
  ) _252_ (
    .I0(_044_),
    .I1(_040_),
    .I2(_041_),
    .I3(1'h0),
    .O(_058_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:52" *)
  SB_LUT4 #(
    .LUT_INIT(16'hd23c)
  ) _253_ (
    .I0(\regB.reg_value [3]),
    .I1(_039_),
    .I2(_060_),
    .I3(\regA.reg_value [6]),
    .O(_061_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:48" *)
  SB_LUT4 #(
    .LUT_INIT(8'h78)
  ) _254_ (
    .I0(\regA.reg_value [4]),
    .I1(\regB.reg_value [5]),
    .I2(_059_),
    .I3(1'h0),
    .O(_060_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h7888)
  ) _255_ (
    .I0(\regB.reg_value [2]),
    .I1(\regA.reg_value [7]),
    .I2(\regB.reg_value [4]),
    .I3(\regA.reg_value [5]),
    .O(_059_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h8000)
  ) _256_ (
    .I0(\regB.reg_value [1]),
    .I1(\regB.reg_value [3]),
    .I2(\regA.reg_value [5]),
    .I3(\regA.reg_value [7]),
    .O(_039_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:44" *)
  SB_LUT4 #(
    .LUT_INIT(4'h6)
  ) _257_ (
    .I0(_064_),
    .I1(_062_),
    .I2(1'h0),
    .I3(1'h0),
    .O(_065_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h3c5a)
  ) _258_ (
    .I0(_138_),
    .I1(_042_),
    .I2(_063_),
    .I3(_043_),
    .O(_064_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:44" *)
  SB_LUT4 #(
    .LUT_INIT(4'h8)
  ) _259_ (
    .I0(\regA.reg_value [4]),
    .I1(\regB.reg_value [4]),
    .I2(1'h0),
    .I3(1'h0),
    .O(_138_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:44" *)
  SB_LUT4 #(
    .LUT_INIT(4'h8)
  ) _260_ (
    .I0(\regA.reg_value [3]),
    .I1(\regB.reg_value [6]),
    .I2(1'h0),
    .I3(1'h0),
    .O(_063_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:44" *)
  SB_LUT4 #(
    .LUT_INIT(4'h8)
  ) _261_ (
    .I0(\regA.reg_value [2]),
    .I1(\regB.reg_value [7]),
    .I2(1'h0),
    .I3(1'h0),
    .O(_062_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h0f77)
  ) _262_ (
    .I0(\regB.reg_value [6]),
    .I1(\regA.reg_value [2]),
    .I2(_046_),
    .I3(_048_),
    .O(_056_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:44" *)
  SB_LUT4 #(
    .LUT_INIT(4'h4)
  ) _263_ (
    .I0(_067_),
    .I1(_055_),
    .I2(1'h0),
    .I3(1'h0),
    .O(_069_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h1ee1)
  ) _264_ (
    .I0(_139_),
    .I1(_068_),
    .I2(_082_),
    .I3(_070_),
    .O(mul_val[10])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h00f1)
  ) _265_ (
    .I0(_034_),
    .I1(_053_),
    .I2(_052_),
    .I3(_069_),
    .O(_139_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:48" *)
  SB_LUT4 #(
    .LUT_INIT(8'h96)
  ) _266_ (
    .I0(_081_),
    .I1(_072_),
    .I2(_071_),
    .I3(1'h0),
    .O(_082_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:48" *)
  SB_LUT4 #(
    .LUT_INIT(8'h69)
  ) _267_ (
    .I0(_080_),
    .I1(_073_),
    .I2(_077_),
    .I3(1'h0),
    .O(_081_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h7887)
  ) _268_ (
    .I0(\regA.reg_value [4]),
    .I1(\regB.reg_value [6]),
    .I2(_079_),
    .I3(_078_),
    .O(_080_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h007f)
  ) _269_ (
    .I0(\regB.reg_value [5]),
    .I1(_059_),
    .I2(\regA.reg_value [4]),
    .I3(_140_),
    .O(_079_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:48" *)
  SB_LUT4 #(
    .LUT_INIT(8'h80)
  ) _270_ (
    .I0(_024_),
    .I1(\regB.reg_value [4]),
    .I2(\regA.reg_value [7]),
    .I3(1'h0),
    .O(_140_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:44" *)
  SB_LUT4 #(
    .LUT_INIT(4'h8)
  ) _271_ (
    .I0(\regA.reg_value [3]),
    .I1(\regB.reg_value [7]),
    .I2(1'h0),
    .I3(1'h0),
    .O(_078_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h133f)
  ) _272_ (
    .I0(\regB.reg_value [3]),
    .I1(_039_),
    .I2(_060_),
    .I3(\regA.reg_value [6]),
    .O(_073_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:48" *)
  SB_LUT4 #(
    .LUT_INIT(8'h78)
  ) _273_ (
    .I0(\regB.reg_value [3]),
    .I1(\regA.reg_value [7]),
    .I2(_075_),
    .I3(1'h0),
    .O(_077_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h7888)
  ) _274_ (
    .I0(\regB.reg_value [4]),
    .I1(\regA.reg_value [6]),
    .I2(\regB.reg_value [5]),
    .I3(\regA.reg_value [5]),
    .O(_075_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:48" *)
  SB_LUT4 #(
    .LUT_INIT(8'h2b)
  ) _275_ (
    .I0(_058_),
    .I1(_061_),
    .I2(_065_),
    .I3(1'h0),
    .O(_072_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h0f77)
  ) _276_ (
    .I0(\regB.reg_value [6]),
    .I1(\regA.reg_value [3]),
    .I2(_062_),
    .I3(_064_),
    .O(_071_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:48" *)
  SB_LUT4 #(
    .LUT_INIT(8'hb2)
  ) _277_ (
    .I0(_057_),
    .I1(_066_),
    .I2(_056_),
    .I3(1'h0),
    .O(_070_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:48" *)
  SB_LUT4 #(
    .LUT_INIT(8'h96)
  ) _278_ (
    .I0(_083_),
    .I1(_084_),
    .I2(_092_),
    .I3(1'h0),
    .O(mul_val[11])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h5701)
  ) _279_ (
    .I0(_082_),
    .I1(_068_),
    .I2(_139_),
    .I3(_070_),
    .O(_083_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:48" *)
  SB_LUT4 #(
    .LUT_INIT(8'hd4)
  ) _280_ (
    .I0(_081_),
    .I1(_072_),
    .I2(_071_),
    .I3(1'h0),
    .O(_084_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:48" *)
  SB_LUT4 #(
    .LUT_INIT(8'h96)
  ) _281_ (
    .I0(_086_),
    .I1(_085_),
    .I2(_091_),
    .I3(1'h0),
    .O(_092_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:48" *)
  SB_LUT4 #(
    .LUT_INIT(8'h71)
  ) _282_ (
    .I0(_080_),
    .I1(_077_),
    .I2(_073_),
    .I3(1'h0),
    .O(_086_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h2bbb)
  ) _283_ (
    .I0(_079_),
    .I1(_078_),
    .I2(\regA.reg_value [4]),
    .I3(\regB.reg_value [6]),
    .O(_085_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:48" *)
  SB_LUT4 #(
    .LUT_INIT(8'h96)
  ) _284_ (
    .I0(_076_),
    .I1(_090_),
    .I2(_088_),
    .I3(1'h0),
    .O(_091_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:48" *)
  SB_LUT4 #(
    .LUT_INIT(8'h80)
  ) _285_ (
    .I0(_075_),
    .I1(\regB.reg_value [3]),
    .I2(\regA.reg_value [7]),
    .I3(1'h0),
    .O(_076_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:52" *)
  SB_LUT4 #(
    .LUT_INIT(16'hd23c)
  ) _286_ (
    .I0(\regA.reg_value [5]),
    .I1(_074_),
    .I2(_089_),
    .I3(\regB.reg_value [6]),
    .O(_090_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h8000)
  ) _287_ (
    .I0(\regB.reg_value [4]),
    .I1(\regB.reg_value [5]),
    .I2(\regA.reg_value [5]),
    .I3(\regA.reg_value [6]),
    .O(_074_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:44" *)
  SB_LUT4 #(
    .LUT_INIT(4'h8)
  ) _288_ (
    .I0(\regA.reg_value [4]),
    .I1(\regB.reg_value [7]),
    .I2(1'h0),
    .I3(1'h0),
    .O(_089_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h7888)
  ) _289_ (
    .I0(\regB.reg_value [4]),
    .I1(\regA.reg_value [7]),
    .I2(\regB.reg_value [5]),
    .I3(\regA.reg_value [6]),
    .O(_088_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h8e71)
  ) _290_ (
    .I0(_083_),
    .I1(_084_),
    .I2(_092_),
    .I3(_103_),
    .O(mul_val[12])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:44" *)
  SB_LUT4 #(
    .LUT_INIT(4'h9)
  ) _291_ (
    .I0(_093_),
    .I1(_101_),
    .I2(1'h0),
    .I3(1'h0),
    .O(_103_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:48" *)
  SB_LUT4 #(
    .LUT_INIT(8'hb2)
  ) _292_ (
    .I0(_086_),
    .I1(_091_),
    .I2(_085_),
    .I3(1'h0),
    .O(_093_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:48" *)
  SB_LUT4 #(
    .LUT_INIT(8'h96)
  ) _293_ (
    .I0(_095_),
    .I1(_100_),
    .I2(_094_),
    .I3(1'h0),
    .O(_101_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:48" *)
  SB_LUT4 #(
    .LUT_INIT(8'h17)
  ) _294_ (
    .I0(_076_),
    .I1(_090_),
    .I2(_088_),
    .I3(1'h0),
    .O(_095_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:48" *)
  SB_LUT4 #(
    .LUT_INIT(8'h78)
  ) _295_ (
    .I0(\regB.reg_value [5]),
    .I1(\regA.reg_value [7]),
    .I2(_098_),
    .I3(1'h0),
    .O(_100_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:52" *)
  SB_LUT4 #(
    .LUT_INIT(16'hd23c)
  ) _296_ (
    .I0(\regA.reg_value [6]),
    .I1(_087_),
    .I2(_096_),
    .I3(\regB.reg_value [6]),
    .O(_098_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h8000)
  ) _297_ (
    .I0(\regB.reg_value [4]),
    .I1(\regB.reg_value [5]),
    .I2(\regA.reg_value [6]),
    .I3(\regA.reg_value [7]),
    .O(_087_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:44" *)
  SB_LUT4 #(
    .LUT_INIT(4'h8)
  ) _298_ (
    .I0(\regA.reg_value [5]),
    .I1(\regB.reg_value [7]),
    .I2(1'h0),
    .I3(1'h0),
    .O(_096_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h133f)
  ) _299_ (
    .I0(\regA.reg_value [5]),
    .I1(_074_),
    .I2(_089_),
    .I3(\regB.reg_value [6]),
    .O(_094_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h1ee1)
  ) _300_ (
    .I0(_141_),
    .I1(_102_),
    .I2(_104_),
    .I3(_108_),
    .O(mul_val[13])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h7100)
  ) _301_ (
    .I0(_083_),
    .I1(_084_),
    .I2(_092_),
    .I3(_103_),
    .O(_141_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:44" *)
  SB_LUT4 #(
    .LUT_INIT(4'h4)
  ) _302_ (
    .I0(_093_),
    .I1(_101_),
    .I2(1'h0),
    .I3(1'h0),
    .O(_102_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:48" *)
  SB_LUT4 #(
    .LUT_INIT(8'hb2)
  ) _303_ (
    .I0(_095_),
    .I1(_100_),
    .I2(_094_),
    .I3(1'h0),
    .O(_104_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:48" *)
  SB_LUT4 #(
    .LUT_INIT(8'h69)
  ) _304_ (
    .I0(_099_),
    .I1(_105_),
    .I2(_107_),
    .I3(1'h0),
    .O(_108_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:48" *)
  SB_LUT4 #(
    .LUT_INIT(8'h80)
  ) _305_ (
    .I0(_098_),
    .I1(\regB.reg_value [5]),
    .I2(\regA.reg_value [7]),
    .I3(1'h0),
    .O(_099_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h133f)
  ) _306_ (
    .I0(\regA.reg_value [6]),
    .I1(_087_),
    .I2(_096_),
    .I3(\regB.reg_value [6]),
    .O(_105_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h7888)
  ) _307_ (
    .I0(\regA.reg_value [6]),
    .I1(\regB.reg_value [7]),
    .I2(\regB.reg_value [6]),
    .I3(\regA.reg_value [7]),
    .O(_107_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:52" *)
  SB_LUT4 #(
    .LUT_INIT(16'hb44b)
  ) _308_ (
    .I0(_097_),
    .I1(_106_),
    .I2(_110_),
    .I3(_109_),
    .O(mul_val[14])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:52" *)
  SB_LUT4 #(
    .LUT_INIT(16'hddd4)
  ) _309_ (
    .I0(_104_),
    .I1(_108_),
    .I2(_141_),
    .I3(_102_),
    .O(_110_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:48" *)
  SB_LUT4 #(
    .LUT_INIT(8'h71)
  ) _310_ (
    .I0(_099_),
    .I1(_107_),
    .I2(_105_),
    .I3(1'h0),
    .O(_109_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:44" *)
  SB_LUT4 #(
    .LUT_INIT(4'h8)
  ) _311_ (
    .I0(\regA.reg_value [6]),
    .I1(\regB.reg_value [6]),
    .I2(1'h0),
    .I3(1'h0),
    .O(_097_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:44" *)
  SB_LUT4 #(
    .LUT_INIT(4'h8)
  ) _312_ (
    .I0(\regA.reg_value [7]),
    .I1(\regB.reg_value [7]),
    .I2(1'h0),
    .I3(1'h0),
    .O(_106_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:52" *)
  SB_LUT4 #(
    .LUT_INIT(16'hc8fc)
  ) _313_ (
    .I0(_097_),
    .I1(_106_),
    .I2(_110_),
    .I3(_109_),
    .O(mul_val[15])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:44" *)
  SB_LUT4 #(
    .LUT_INIT(4'h9)
  ) _314_ (
    .I0(_000_),
    .I1(_147_),
    .I2(1'h0),
    .I3(1'h0),
    .O(mul_val[5])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/ice40/cells_map.v:40" *)
  SB_LUT4 #(
    .LUT_INIT(2'h1)
  ) _315_ (
    .I0(rstn),
    .I1(1'h0),
    .I2(1'h0),
    .I3(1'h0),
    .O(_149_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "rtl/unsigned_mult.sv:18|rtl/register8bit.sv:12|/usr/bin/../share/yosys/ice40/cells_map.v:12" *)
  SB_DFFR _316_ (
    .C(clk),
    .D(a[0]),
    .Q(\regA.reg_value [0]),
    .R(_149_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "rtl/unsigned_mult.sv:18|rtl/register8bit.sv:12|/usr/bin/../share/yosys/ice40/cells_map.v:12" *)
  SB_DFFR _317_ (
    .C(clk),
    .D(a[1]),
    .Q(\regA.reg_value [1]),
    .R(_149_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "rtl/unsigned_mult.sv:18|rtl/register8bit.sv:12|/usr/bin/../share/yosys/ice40/cells_map.v:12" *)
  SB_DFFR _318_ (
    .C(clk),
    .D(a[2]),
    .Q(\regA.reg_value [2]),
    .R(_149_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "rtl/unsigned_mult.sv:18|rtl/register8bit.sv:12|/usr/bin/../share/yosys/ice40/cells_map.v:12" *)
  SB_DFFR _319_ (
    .C(clk),
    .D(a[3]),
    .Q(\regA.reg_value [3]),
    .R(_149_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "rtl/unsigned_mult.sv:18|rtl/register8bit.sv:12|/usr/bin/../share/yosys/ice40/cells_map.v:12" *)
  SB_DFFR _320_ (
    .C(clk),
    .D(a[4]),
    .Q(\regA.reg_value [4]),
    .R(_149_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "rtl/unsigned_mult.sv:18|rtl/register8bit.sv:12|/usr/bin/../share/yosys/ice40/cells_map.v:12" *)
  SB_DFFR _321_ (
    .C(clk),
    .D(a[5]),
    .Q(\regA.reg_value [5]),
    .R(_149_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "rtl/unsigned_mult.sv:18|rtl/register8bit.sv:12|/usr/bin/../share/yosys/ice40/cells_map.v:12" *)
  SB_DFFR _322_ (
    .C(clk),
    .D(a[6]),
    .Q(\regA.reg_value [6]),
    .R(_149_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "rtl/unsigned_mult.sv:18|rtl/register8bit.sv:12|/usr/bin/../share/yosys/ice40/cells_map.v:12" *)
  SB_DFFR _323_ (
    .C(clk),
    .D(a[7]),
    .Q(\regA.reg_value [7]),
    .R(_149_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "rtl/unsigned_mult.sv:20|rtl/register8bit.sv:12|/usr/bin/../share/yosys/ice40/cells_map.v:12" *)
  SB_DFFR _324_ (
    .C(clk),
    .D(b[0]),
    .Q(\regB.reg_value [0]),
    .R(_149_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "rtl/unsigned_mult.sv:20|rtl/register8bit.sv:12|/usr/bin/../share/yosys/ice40/cells_map.v:12" *)
  SB_DFFR _325_ (
    .C(clk),
    .D(b[1]),
    .Q(\regB.reg_value [1]),
    .R(_149_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "rtl/unsigned_mult.sv:20|rtl/register8bit.sv:12|/usr/bin/../share/yosys/ice40/cells_map.v:12" *)
  SB_DFFR _326_ (
    .C(clk),
    .D(b[2]),
    .Q(\regB.reg_value [2]),
    .R(_149_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "rtl/unsigned_mult.sv:20|rtl/register8bit.sv:12|/usr/bin/../share/yosys/ice40/cells_map.v:12" *)
  SB_DFFR _327_ (
    .C(clk),
    .D(b[3]),
    .Q(\regB.reg_value [3]),
    .R(_149_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "rtl/unsigned_mult.sv:20|rtl/register8bit.sv:12|/usr/bin/../share/yosys/ice40/cells_map.v:12" *)
  SB_DFFR _328_ (
    .C(clk),
    .D(b[4]),
    .Q(\regB.reg_value [4]),
    .R(_149_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "rtl/unsigned_mult.sv:20|rtl/register8bit.sv:12|/usr/bin/../share/yosys/ice40/cells_map.v:12" *)
  SB_DFFR _329_ (
    .C(clk),
    .D(b[5]),
    .Q(\regB.reg_value [5]),
    .R(_149_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "rtl/unsigned_mult.sv:20|rtl/register8bit.sv:12|/usr/bin/../share/yosys/ice40/cells_map.v:12" *)
  SB_DFFR _330_ (
    .C(clk),
    .D(b[6]),
    .Q(\regB.reg_value [6]),
    .R(_149_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "rtl/unsigned_mult.sv:20|rtl/register8bit.sv:12|/usr/bin/../share/yosys/ice40/cells_map.v:12" *)
  SB_DFFR _331_ (
    .C(clk),
    .D(b[7]),
    .Q(\regB.reg_value [7]),
    .R(_149_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "rtl/unsigned_mult.sv:26|rtl/register16bit.sv:12|/usr/bin/../share/yosys/ice40/cells_map.v:12" *)
  SB_DFFR _332_ (
    .C(clk),
    .D(mul_val[0]),
    .Q(\regOut.reg_value [0]),
    .R(_149_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "rtl/unsigned_mult.sv:26|rtl/register16bit.sv:12|/usr/bin/../share/yosys/ice40/cells_map.v:12" *)
  SB_DFFR _333_ (
    .C(clk),
    .D(mul_val[1]),
    .Q(\regOut.reg_value [1]),
    .R(_149_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "rtl/unsigned_mult.sv:26|rtl/register16bit.sv:12|/usr/bin/../share/yosys/ice40/cells_map.v:12" *)
  SB_DFFR _334_ (
    .C(clk),
    .D(mul_val[2]),
    .Q(\regOut.reg_value [2]),
    .R(_149_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "rtl/unsigned_mult.sv:26|rtl/register16bit.sv:12|/usr/bin/../share/yosys/ice40/cells_map.v:12" *)
  SB_DFFR _335_ (
    .C(clk),
    .D(mul_val[3]),
    .Q(\regOut.reg_value [3]),
    .R(_149_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "rtl/unsigned_mult.sv:26|rtl/register16bit.sv:12|/usr/bin/../share/yosys/ice40/cells_map.v:12" *)
  SB_DFFR _336_ (
    .C(clk),
    .D(mul_val[4]),
    .Q(\regOut.reg_value [4]),
    .R(_149_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "rtl/unsigned_mult.sv:26|rtl/register16bit.sv:12|/usr/bin/../share/yosys/ice40/cells_map.v:12" *)
  SB_DFFR _337_ (
    .C(clk),
    .D(mul_val[5]),
    .Q(\regOut.reg_value [5]),
    .R(_149_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "rtl/unsigned_mult.sv:26|rtl/register16bit.sv:12|/usr/bin/../share/yosys/ice40/cells_map.v:12" *)
  SB_DFFR _338_ (
    .C(clk),
    .D(mul_val[6]),
    .Q(\regOut.reg_value [6]),
    .R(_149_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "rtl/unsigned_mult.sv:26|rtl/register16bit.sv:12|/usr/bin/../share/yosys/ice40/cells_map.v:12" *)
  SB_DFFR _339_ (
    .C(clk),
    .D(mul_val[7]),
    .Q(\regOut.reg_value [7]),
    .R(_149_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "rtl/unsigned_mult.sv:26|rtl/register16bit.sv:12|/usr/bin/../share/yosys/ice40/cells_map.v:12" *)
  SB_DFFR _340_ (
    .C(clk),
    .D(mul_val[8]),
    .Q(\regOut.reg_value [8]),
    .R(_149_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "rtl/unsigned_mult.sv:26|rtl/register16bit.sv:12|/usr/bin/../share/yosys/ice40/cells_map.v:12" *)
  SB_DFFR _341_ (
    .C(clk),
    .D(mul_val[9]),
    .Q(\regOut.reg_value [9]),
    .R(_149_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "rtl/unsigned_mult.sv:26|rtl/register16bit.sv:12|/usr/bin/../share/yosys/ice40/cells_map.v:12" *)
  SB_DFFR _342_ (
    .C(clk),
    .D(mul_val[10]),
    .Q(\regOut.reg_value [10]),
    .R(_149_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "rtl/unsigned_mult.sv:26|rtl/register16bit.sv:12|/usr/bin/../share/yosys/ice40/cells_map.v:12" *)
  SB_DFFR _343_ (
    .C(clk),
    .D(mul_val[11]),
    .Q(\regOut.reg_value [11]),
    .R(_149_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "rtl/unsigned_mult.sv:26|rtl/register16bit.sv:12|/usr/bin/../share/yosys/ice40/cells_map.v:12" *)
  SB_DFFR _344_ (
    .C(clk),
    .D(mul_val[12]),
    .Q(\regOut.reg_value [12]),
    .R(_149_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "rtl/unsigned_mult.sv:26|rtl/register16bit.sv:12|/usr/bin/../share/yosys/ice40/cells_map.v:12" *)
  SB_DFFR _345_ (
    .C(clk),
    .D(mul_val[13]),
    .Q(\regOut.reg_value [13]),
    .R(_149_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "rtl/unsigned_mult.sv:26|rtl/register16bit.sv:12|/usr/bin/../share/yosys/ice40/cells_map.v:12" *)
  SB_DFFR _346_ (
    .C(clk),
    .D(mul_val[14]),
    .Q(\regOut.reg_value [14]),
    .R(_149_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "rtl/unsigned_mult.sv:26|rtl/register16bit.sv:12|/usr/bin/../share/yosys/ice40/cells_map.v:12" *)
  SB_DFFR _347_ (
    .C(clk),
    .D(mul_val[15]),
    .Q(\regOut.reg_value [15]),
    .R(_149_)
  );
  assign a_reg = \regA.reg_value ;
  assign b_reg = \regB.reg_value ;
  assign out = \regOut.reg_value ;
  assign out_reg = \regOut.reg_value ;
  assign \regA.clk  = clk;
  assign \regA.in  = a;
  assign \regA.out  = \regA.reg_value ;
  assign \regA.rstn  = rstn;
  assign \regB.clk  = clk;
  assign \regB.in  = b;
  assign \regB.out  = \regB.reg_value ;
  assign \regB.rstn  = rstn;
  assign \regOut.clk  = clk;
  assign \regOut.in  = mul_val;
  assign \regOut.out  = \regOut.reg_value ;
  assign \regOut.rstn  = rstn;
endmodule
